---
abstract: 'Get a user''s existing config directory, or copy in defaults'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.11
  File::Remove: 1.42
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: File::UserConfig
name: File-UserConfig
no_index:
  directory:
    - share
    - share
    - inc
    - t
requires:
  Carp: 0
  File::Copy::Recursive: 0.18
  File::HomeDir: 0.51
  File::ShareDir: 1.00
  File::Spec: 0.80
  perl: 5.005
resources:
  license: http://dev.perl.org/licenses/
version: 0.06
